on:
  workflow_call:
    inputs:
      cleanup-artifacts:
        type: boolean
        default: false
        description: Removes any artifacts generated during this workflow
  push:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  cleanup-artifacts:
    name: Artifacts
    runs-on: ubuntu-latest
    # if: ${{ inputs.cleanup-artifacts }}
    steps:
      - run: echo "${{github.run_id}}" > artifact.txt
      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: agent
          path: artifact.txt
          retention-days: 1
      - run: |
          gh config set prompt disabled
          gh api -H "Accept: application/json" /repos/${{ github.repository }}/actions/artifacts \
            | jq --raw-output '.artifacts[] | select(.workflow_run.id == ${{ github.run_id }}) | .id' \
            | xargs -I {} -n1 gh api -i --method DELETE -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/artifacts/{}