on:
  workflow_call:
    inputs:
      context:
        type: string
        default: .
      dockerfile:
        type: string

jobs:
  Containerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set outputs
        id: sha
        run: |
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
          echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{inputs.context}}
          file: ${{inputs.dockerfile}}
          push: true
          tags: ghcr.io/${{github.repository}}:${{github.sha}}
          cache-from: type=registry,ref=ghcr.io/${{github.repository}}:latest
          cache-to: type=inline
          build-args: |
            VERSION=${{steps.sha.outputs.tag}}
            HASH=${{steps.sha.outputs.sha}}