on:
  workflow_call:
    inputs:
      target-repo:
        type: string
        description: The repository to perform the customizations
        default: "printtracker/ci-infra"
      target-branch:
        type: string
        description: The target branch to perform the customizations
        default: master
      target-repo-token:
        type: string
        description: A Github personal access token for the target repo
      image:
        type: string
        description: The container image to kustomize
      image-tag:
        type: string
        description: The new container image tag
      tagged-image:
        type: string
        description: The new image with a tag that should be customize
      deploy-envs:
        required: true
        type: string
        description: A comma-separated list of environments should be deployed, for example "dev", or "dev,prod", or "prod"

jobs:
  Kustomize:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    concurrency: git-checkout-${{inputs.target-repo}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{inputs.target-repo}}
          token: ${{secrets.BOT_TOKEN}}
          path: infra
      - name: Variables
        id: vars
        if: ${{ inputs.tagged-image != '' }}
        run: |
          echo "::set-output name=image::$(echo '${{ inputs.tagged-image |  | cut -d ':' -f1 }}')"
          echo "::set-output name=image-tag::$(echo '${{ inputs.tagged-image |  | cut -d ':' -f2 }}')"
      - name: Variables
        id: vars
        if: ${{ inputs.tagged-image == '' }}
        run: |
          echo "::set-output name=image::${{inputs.image}}"
          echo "::set-output name=image-tag::${{inputs.image-tag}}""
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.1.0"
      - name: Configure git
        run: |
          cd infra
          git config --global user.email "bot@ptkr.io"
          git config --global user.name "Print Tracker Bot"
      - name: Kustomize
        run: |
          cd infra
          target_dirs=$(find $(jq -r 'split(",") | map("./kube/deploy/" + .) | join(" ")' -Rc <(echo '${{inputs.deploy-envs}}')) \
            -type f \
            -name kustomization.yml -o -name kustomization.yaml \
            -exec grep -q "${{steps.vars.outputs.image}}" {} \; \
            -print | xargs dirname)

          for dn in ${target_dirs}; do
              pushd "${dn}"
              kustomize edit set image ${{steps.vars.outputs.image}}:${{steps.vars.outputs.image-tag}}
              popd
              echo
          done
      - name: Commit and Push
        run: |
          cd infra
          set -e
          git commit -am "Set ${{steps.vars.outputs.image}} image tag to '${{steps.vars.outputs.image}}:${{steps.vars.outputs.image-tag}}'"
          git push origin master