on:
  workflow_call:
    inputs:
      target-repo:
        type: string
        description: The repository to perform the customizations
        default: printtracker/ci-infra
      target-branch:
        type: string
        description: The target branch to perform the customizations
        default: master
      target-repo-token:
        type: string
        description: A Github personal access token for the target repo
      image:
        required: true
        type: string
        description: The container image to kustomize
      image-tag:
        required: true
        type: string
        description: The new container image tag
      deploy-envs:
        required: true
        type: string
        description: A comma-separated list of environments should be deployed, for example "dev", or "dev,prod", or "prod"

jobs:
  Kustomize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{inputs.target_repo}}
          token: ${{inputs.target-repo-token || secrets.BOT_TOKEN}}
          path: infra
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.1.0"
      - name: Configure git
        run: |
          cd infra
          git config --global user.email "bot@ptkr.io"
          git config --global user.name "Print Tracker Bot"
      - name: Kustomize
        run: |
          cd infra
          target_dirs=$(find $(jq -r 'split(",") | map("./kube/deploy/" + .) | join(" ")' -Rc <(echo '${{inputs.deploy-envs}}')) \
            -type f \
            -name kustomization.yml -o -name kustomization.yaml \
            -exec grep -q "${{inputs.image}}" {} \; \
            -print | xargs dirname)

          for dn in ${target_dirs}; do
              pushd "${dn}"
              kustomize edit set image ${{inputs.image}}:${{inputs.image-tag}}
              popd
              echo
          done
      - name: Commit and Push
        run: |
          cd infra
          git add .
          git commit -m "Set ${{inputs.image}} image tag to '${{inputs.image}}:${{inputs.image-tag}}'"
          git push origin master