on:
  workflow_call:
    outputs:
      tag:
        description: The tag of the image that was created
        value: ${{jobs.Version.outputs.tag}}

jobs:
  Version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{steps.git.outputs.tag}}
      sha: ${{steps.git.outputs.sha}}
      ref: ${{steps.git.outputs.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set tag and hash
        id: git
        run: |
          export HASH=$(git rev-parse --short HEAD);
          export VERSION=$(git describe --tags);
          FIRST=$(git describe --tags|sed 's/^\(.\).*/\1/');
          if [ "$FIRST" == "v" ]; then 
            VERSION=$(git describe --tags|sed 's/^.\{1\}//');
          fi
          echo $HASH
          echo $VERSION

          # If the version is empty, then set the version to the hash
          # otherwise set the version to the git tag
          if [ "$VERSION" == "" ]; then 
            echo "::set-output name=tag::$HASH"
          else
            echo "::set-output name=tag::$VERSION"
          fi
          echo "::set-output name=sha::$HASH"

          # Reformat the ref name so that slashes are replaced with underscores.
          # This is required if we want to use the ref name as a Docker tag
          echo "::set-output name=ref::$(echo '${{github.head_ref || github.ref_name}}' | sed 's/\//_/')"