on:
  workflow_call:
    outputs:
      tag:
        description: The git tag
        value: ${{jobs.Version.outputs.tag}}
      sha:
        description: The git sha (short version)
        value: ${{jobs.Version.outputs.sha}}
      ref:
        description: The git ref
        value: ${{jobs.Version.outputs.ref}}

jobs:
  Version:
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, Linux]
    outputs:
      tag: ${{steps.git.outputs.tag}}
      exact-tag: ${{steps.git.outputs.exact-tag}}
      closest-tag: ${{steps.git.outputs.closest-tag}}
      sha: ${{steps.git.outputs.sha}}
      ref: ${{steps.git.outputs.ref}}
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.BOT_SSH_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set tag and hash
        id: git
        run: |
          export HASH=$(git rev-parse --short HEAD);
          export EXACT_TAG=$(git describe --exact-match HEAD);
          export CLOSEST_TAG=$(git describe --always --tags | cut -d- -f1);
          export VERSION=$(git describe --always --tags);
          export REF=$(echo '${{github.head_ref || github.ref_name}}' | sed 's/\//_/')
          FIRST=$(git describe --always --tags|sed 's/^\(.\).*/\1/');
          if [ "$FIRST" == "v" ]; then 
            VERSION=$(git describe --always --tags|sed 's/^.\{1\}//');
          fi

          echo 'Ref:' $REF
          echo 'Hash:' $HASH
          echo 'Version:' $VERSION
          echo 'Exact tag:' $EXACT_TAG
          echo 'Closest tag:' $CLOSEST_TAG

          # Reformat the ref name so that slashes are replaced with underscores.
          # This is required if we want to use the ref name as a Docker tag
          echo "ref=$REF" >> $GITHUB_OUTPUT
          echo "sha=$HASH" >> $GITHUB_OUTPUT
          echo "tag=$VERSION" >> $GITHUB_OUTPUT
          echo "exact-tag=$EXACT_TAG" >> $GITHUB_OUTPUT
          echo "exact_tag=$EXACT_TAG" >> $GITHUB_OUTPUT
          echo "closest-tag=$CLOSEST_TAG" >> $GITHUB_OUTPUT
          echo "closest_tag=$CLOSEST_TAG" >> $GITHUB_OUTPUT
          
          echo "::notice title=Version::$VERSION"