on:
  workflow_call:
    outputs:
      tag:
        description: The git tag
        value: ${{jobs.Version.outputs.tag}}
      sha:
        description: The git sha (short version)
        value: ${{jobs.Version.outputs.sha}}
      ref:
        description: The git ref
        value: ${{jobs.Version.outputs.ref}}

jobs:
  Version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{steps.git.outputs.tag}}
      sha: ${{steps.git.outputs.sha}}
      ref: ${{steps.git.outputs.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set tag and hash
        id: git
        run: |
          export HASH=$(git rev-parse --short HEAD);
          export VERSION=$(git describe --always --tags);
          FIRST=$(git describe --always --tags|sed 's/^\(.\).*/\1/');
          if [ "$FIRST" == "v" ]; then 
            VERSION=$(git describe --always --tags|sed 's/^.\{1\}//');
          fi
          echo $HASH
          echo $VERSION

          # Reformat the ref name so that slashes are replaced with underscores.
          # This is required if we want to use the ref name as a Docker tag
          echo "::set-output name=ref::$(echo '${{github.head_ref || github.ref_name}}' | sed 's/\//_/')"
          echo "::set-output name=sha::$HASH"
          echo "::set-output name=tag::$VERSION"